export const PO_FORM_LABELS = {
  company: "Nama Company",
  inisial: "Inisial",
  tujuan: "Tujuan (Toko/DC)",
  noPo: "Nomor PO",
  tglPo: "Tanggal PO",
  expiredTgl: "Tanggal Expired",
  regional: "Regional",
  siteArea: "Site Area",
  linkPo: "Link PO (GDrive)",
  noInvoice: "No Invoice",
  remarks: "Remarks",
  checklistDokumen: "Checklist Dokumen",
  namaProduk: "Nama Produk",
  pcs: "PCS",
  hargaPcs: "Harga/Pcs",
  pcsKirim: "PCS Kirim",
  discount: "Discount",
  nominal: "Nominal",
  rpTagih: "Rp Tagih",
  aksi: "Aksi",
  preview: "Preview",
  tambahItem: "Tambah Item",
} as const;
